use_frameworks!

platform :ios, '12.0'

target 'AdServiceManager_Example' do
  pod 'AdServiceManager', :path => '../'
  pod 'Alamofire', '4.7'
  
  target 'AdServiceManager_Tests' do
    inherit! :search_paths

    
  end
end
